language: go

go:
- 1.8.x
- 1.9.x
- 1.x
- master

before_install:
- go get github.com/Masterminds/glide

install:
- glide install
- go install

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
